### ISSUE TITLE
Do i need to update from version 2.0.0?

### ISSUE THREAD

**Issue by tracer8** [eggheadgames/android-in-app-payments#31]
Hi,
My apps is currently using version 2.0.0. Do i need to update to 3.0.0?
I checked releases, but not found any critical issues.
Thank you for very good IAP Lib!

**Comment by mikemee** [comment]
@tracer8 I would at least update to 2.1.0 to get the various bug fixes.  

Version 3.0.0 has no changed functionality, but it was necessary for one of my apps because Google detected the Amazon IAP library there and decided it was a privacy violation (perhaps this is a valid conclusion, I don't know). See #30 for the details. Google hasn't flagged any of my other apps that use this same library, but I figure it's just a matter of time. So, it's really up to you. 

If you're already using flavors in your Gradle file for Amazon vs Google builds, then it's trivial change. However, if you're not, I understand how flavors can be a bit intimidating the first time you use them. I have found them to be really handy and I use them for Android Manifest file differences between Google and Amazon, for example.

I hope this helps!
